name: Deploy to Cloud Run from Source
on:
  push:
    branches: [ "master" ]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Add a fake 'git' to the PATH to force checkout to download zipball instead
        run: |
          echo echo hello > git.bat
          echo ::add-path::%CD%
        shell: cmd
      - uses: actions/checkout@v2
        with:
         path: .
