name: Deploy to Run
on:
  push:
    branches: [ "master" ]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: download data
        uses: actions/checkout@v3
        with:
         path: .
      - name: move data
        uses: canastro/copy-file-action@master
        with:
         source: "/home/ubuntu/actions-runner/_work/nayan/nayan/*"
         target: "/var/www/html/*"
