name: Deploy to Run
on:
  push:
    branches: [ "master" ]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: download data
        uses: actions/checkout@v3
        with:
         path: .
      -  shell: bash
         run: |
          sudo mv /home/ubuntu/actions-runner/_work/nayan/nayan/* /var/www/html/

